### ISSUE TITLE
Update to 0.8.x

### ISSUE THREAD

**Issue by CapivaraTupiniquim** [ardittristan/VTTFPSMeter#4]
Helo! I really like the module and would like to know if it will be updated.

**Comment by ardittristan** [comment]
it is, the compatible core version even has a 0.8.x version in it

**Comment by CapivaraTupiniquim** [comment]
Could you help me with a question? I don't understand how the module works, so I would like to know if the new version (0.8.8) affects the module in the current compatible version (0.8.1).

**Comment by ardittristan** [comment]
It should not affect it generally, unless the 2nd number (8 in this case) changes, breaking changes don't happen very often!
