### ISSUE TITLE
Uncaught TypeError: Cannot read property 'height' of undefined at updateFPS (fpsmeter.js:153)

### ISSUE THREAD

**Issue by Doresain** [ardittristan/VTTFPSMeter#5]
Foundry version: 0.8.7
Module version: 1.1.1

When I enable the module, nothing happens. No FPS meter and no console errors. The next time I save my module settings, even if I haven't adjusted FPSMeter's settings from the default, I get these errors in console endlessly, several times a second. 

![fps](https://user-images.githubusercontent.com/26096062/122639902-66f43000-d0b1-11eb-8445-a4438be5cf6e.PNG)

Thanks!

**Comment by ardittristan** [comment]
The error is because the code can't find the fps meter container element while the fps meter is enabled.

Which system are you using? And is this in browser or the electron application? I'm currently unable to reproduce.

**Comment by Doresain** [comment]
Huh, interesting. WIndows 10, Chrome 91. Just a regular old desktop.

**Comment by Doresain** [comment]
Okay - relaunched Chrome and updated to the newest point release and I can no longer reproduce. Problem solved, but frustrating to not know the root cause - RIP.
