### ISSUE TITLE
Update for V9

### ISSUE THREAD

**Issue by PhluXx1** [ardittristan/VTTFPSMeter#7]
Hi thanks for this module really helps test how well scenes are running. Would really appreciate a V9 update do you have any idea when we can expect one?

**Comment by ardittristan** [comment]
It should work fine on V9?

**Comment by PhluXx1** [comment]
Thanks for getting back me so quick and that's good to hear.

Could you please update the [Foundry package page](https://foundryvtt.com/packages/fpsmeter) to show an available version for 9 that way it can be installed more easily from within the Foundry installer?

![image](https://user-images.githubusercontent.com/72770484/148252625-4ddd16db-2495-4991-8bd1-5f63b9e6e9f4.png)

**Comment by ardittristan** [comment]
Done
